name: Reusable AutoPkg Workflow

# Define this as a reusable workflow
on:
  workflow_call:
    inputs:
      recipe_name:
        description: 'Recipe to run (leave empty to just list recipes)'
        required: false
        type: string
        default: ''
      munki_repo_path:
        description: 'Path to Munki repo'
        required: false
        type: string
        default: '/tmp/munki_repo'
      recipe_repos:
        description: 'Additional recipe repositories to add (comma-separated)'
        required: false
        type: string
        default: ''
      upload_results:
        description: 'Whether to upload results as artifacts'
        required: false
        type: boolean
        default: true
      use_pref_file:
        description: 'Whether to use an external preferences file'
        required: false
        type: boolean
        default: false
      pref_file_path:
        description: 'Path to the external preferences file (plist or JSON)'
        required: false
        type: string
        default: '/tmp/autopkg_prefs.plist'
      pref_file_content:
        description: 'Content for the preferences file (base64 encoded)'
        required: false
        type: string
        default: ''
      cache_dir:
        description: 'Location for cached data such as downloads and operations'
        required: false
        type: string
        default: '~/Library/AutoPkg/Cache'
      recipe_search_dirs:
        description: 'Comma-separated list of locations searched for recipes'
        required: false
        type: string
        default: '.'
      recipe_override_dirs:
        description: 'Comma-separated list of locations searched for override files'
        required: false
        type: string
        default: '~/Library/AutoPkg/RecipeOverrides'
      recipe_repo_dir:
        description: 'Parent directory to store recipe repos added with repo-add'
        required: false
        type: string
        default: '~/Library/AutoPkg/RecipeRepos'
      git_path:
        description: 'Absolute path to git binary for repo commands'
        required: false
        type: string
        default: ''
      github_token:
        description: 'GitHub personal access token for making GitHub requests'
        required: false
        type: string
        default: ''
      github_token_path:
        description: 'Path to file containing GitHub personal access token'
        required: false
        type: string
        default: ''
      fail_recipes_without_trust_info:
        description: 'Whether recipes without trust info are prevented from running'
        required: false
        type: boolean
        default: false
    outputs:
      autopkg_version:
        description: 'Installed AutoPkg version'
        value: ${{ jobs.run-autopkg.outputs.autopkg_version }}
      recipes_added:
        description: 'Number of recipe repositories added'
        value: ${{ jobs.run-autopkg.outputs.recipes_added }}

jobs:
  run-autopkg:
    name: Run AutoPkg
    runs-on: macos-latest
    outputs:
      autopkg_version: ${{ steps.install-autopkg.outputs.version }}
      recipes_added: ${{ steps.add-repos.outputs.repos_count }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up environment
        run: |
          echo "Setting up environment for AutoPkg..."
          # Create Munki repo directory if specified
          mkdir -p ${{ inputs.munki_repo_path }}
          
      - name: Verify Git installation
        run: |
          git --version
          which git
    
      - name: Install AutoPkg
        id: install-autopkg
        run: |
          echo "Downloading latest AutoPkg release..."
          # Get latest release URL
          LATEST_RELEASE_URL=$(curl -s https://api.github.com/repos/autopkg/autopkg/releases/latest | grep "browser_download_url.*pkg" | cut -d '"' -f 4)
          echo "Latest AutoPkg release URL: $LATEST_RELEASE_URL"
          
          # Download the package
          curl -L -o /tmp/AutoPkg.pkg "$LATEST_RELEASE_URL"
          
          # Install the package
          sudo /usr/sbin/installer -pkg /tmp/AutoPkg.pkg -target /
          
          # Verify installation and capture version
          VERSION=$(autopkg version)
          echo "AutoPkg $VERSION installed successfully"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      
      - name: Configure preferences via plist file
        if: ${{ inputs.use_pref_file == true }}
        run: |
          echo "Setting up external preferences file..."
          
          # If pref_file_content is provided, decode and write it to the file
          if [ -n "${{ inputs.pref_file_content }}" ]; then
            echo "Creating preferences file from provided content"
            echo "${{ inputs.pref_file_content }}" | base64 --decode > ${{ inputs.pref_file_path }}
          else
            # Create a basic preferences file if none exists
            if [ ! -f "${{ inputs.pref_file_path }}" ]; then
              echo "Creating new preferences file at ${{ inputs.pref_file_path }}"
              
              # Convert recipe search dirs and override dirs into array format
              IFS=',' read -ra SEARCH_DIRS <<< "${{ inputs.recipe_search_dirs || '.,~/Library/AutoPkg/Recipes,/Library/AutoPkg/Recipes' }}"
              IFS=',' read -ra OVERRIDE_DIRS <<< "${{ inputs.recipe_override_dirs || '~/Library/AutoPkg/RecipeOverrides' }}"
              
              # Determine file format based on extension
              if [[ "${{ inputs.pref_file_path }}" == *.json ]]; then
                # Create JSON preferences file
                cat > ${{ inputs.pref_file_path }} << EOF
                {
                  "MUNKI_REPO": "${{ inputs.munki_repo_path }}",
                  "CACHE_DIR": "${{ inputs.cache_dir }}",
                  "RECIPE_REPO_DIR": "${{ inputs.recipe_repo_dir }}",
                  "RECIPE_SEARCH_DIRS": [
                    $(for i in "${!SEARCH_DIRS[@]}"; do 
                      echo "\"${SEARCH_DIRS[$i]}\"$([ $i -lt $((${#SEARCH_DIRS[@]}-1)) ] && echo ',')"; 
                    done)
                  ],
                  "RECIPE_OVERRIDE_DIRS": [
                    $(for i in "${!OVERRIDE_DIRS[@]}"; do 
                      echo "\"${OVERRIDE_DIRS[$i]}\"$([ $i -lt $((${#OVERRIDE_DIRS[@]}-1)) ] && echo ',')"; 
                    done)
                  ]
                  $([ -n "${{ inputs.git_path }}" ] && echo ", \"GIT_PATH\": \"${{ inputs.git_path }}\"")
                  $([ -n "${{ inputs.github_token }}" ] && echo ", \"GITHUB_TOKEN\": \"${{ inputs.github_token }}\"")
                  $([ -n "${{ inputs.github_token_path }}" ] && echo ", \"GITHUB_TOKEN_PATH\": \"${{ inputs.github_token_path }}\"")
                  $([ "${{ inputs.fail_recipes_without_trust_info }}" == "true" ] && echo ", \"FAIL_RECIPES_WITHOUT_TRUST_INFO\": true" || echo ", \"FAIL_RECIPES_WITHOUT_TRUST_INFO\": false")
                }
                EOF
              else
                # Create Plist preferences file
                /usr/libexec/PlistBuddy -c "Add :MUNKI_REPO string ${{ inputs.munki_repo_path }}" ${{ inputs.pref_file_path }}
                /usr/libexec/PlistBuddy -c "Add :CACHE_DIR string ${{ inputs.cache_dir }}" ${{ inputs.pref_file_path }}
                /usr/libexec/PlistBuddy -c "Add :RECIPE_REPO_DIR string ${{ inputs.recipe_repo_dir }}" ${{ inputs.pref_file_path }}
                
                # Add search directories
                /usr/libexec/PlistBuddy -c "Add :RECIPE_SEARCH_DIRS array" ${{ inputs.pref_file_path }}
                for i in "${!SEARCH_DIRS[@]}"; do
                  /usr/libexec/PlistBuddy -c "Add :RECIPE_SEARCH_DIRS:$i string ${SEARCH_DIRS[$i]}" ${{ inputs.pref_file_path }}
                done
                
                # Add override directories
                /usr/libexec/PlistBuddy -c "Add :RECIPE_OVERRIDE_DIRS array" ${{ inputs.pref_file_path }}
                for i in "${!OVERRIDE_DIRS[@]}"; do
                  /usr/libexec/PlistBuddy -c "Add :RECIPE_OVERRIDE_DIRS:$i string ${OVERRIDE_DIRS[$i]}" ${{ inputs.pref_file_path }}
                done
                
                # Add optional parameters if provided
                if [ -n "${{ inputs.git_path }}" ]; then
                  /usr/libexec/PlistBuddy -c "Add :GIT_PATH string ${{ inputs.git_path }}" ${{ inputs.pref_file_path }}
                fi
                
                if [ -n "${{ inputs.github_token }}" ]; then
                  /usr/libexec/PlistBuddy -c "Add :GITHUB_TOKEN string ${{ inputs.github_token }}" ${{ inputs.pref_file_path }}
                fi
                
                if [ -n "${{ inputs.github_token_path }}" ]; then
                  /usr/libexec/PlistBuddy -c "Add :GITHUB_TOKEN_PATH string ${{ inputs.github_token_path }}" ${{ inputs.pref_file_path }}
                fi
                
                # Set FAIL_RECIPES_WITHOUT_TRUST_INFO
                if [ "${{ inputs.fail_recipes_without_trust_info }}" == "true" ]; then
                  /usr/libexec/PlistBuddy -c "Add :FAIL_RECIPES_WITHOUT_TRUST_INFO bool true" ${{ inputs.pref_file_path }}
                else
                  /usr/libexec/PlistBuddy -c "Add :FAIL_RECIPES_WITHOUT_TRUST_INFO bool false" ${{ inputs.pref_file_path }}
                fi
              fi
            else
              echo "Using existing preferences file at ${{ inputs.pref_file_path }}"
              
              # Update key values in the existing file
              if [[ "${{ inputs.pref_file_path }}" == *.json ]]; then
                # For JSON we need jq
                brew install jq
                TMP_FILE=$(mktemp)
                
                # Update each field if provided
                jq '.MUNKI_REPO = "${{ inputs.munki_repo_path }}"' ${{ inputs.pref_file_path }} > $TMP_FILE
                mv $TMP_FILE ${{ inputs.pref_file_path }}
                
                # More complex updates would be needed for arrays and optional values
                # This is simplified for brevity
              else
                # For plist we use PlistBuddy
                
                # Update MUNKI_REPO
                if /usr/libexec/PlistBuddy -c "Print :MUNKI_REPO" ${{ inputs.pref_file_path }} &>/dev/null; then
                  /usr/libexec/PlistBuddy -c "Set :MUNKI_REPO ${{ inputs.munki_repo_path }}" ${{ inputs.pref_file_path }}
                else
                  /usr/libexec/PlistBuddy -c "Add :MUNKI_REPO string ${{ inputs.munki_repo_path }}" ${{ inputs.pref_file_path }}
                fi
                
                # Update CACHE_DIR if provided
                if [ -n "${{ inputs.cache_dir }}" ]; then
                  if /usr/libexec/PlistBuddy -c "Print :CACHE_DIR" ${{ inputs.pref_file_path }} &>/dev/null; then
                    /usr/libexec/PlistBuddy -c "Set :CACHE_DIR ${{ inputs.cache_dir }}" ${{ inputs.pref_file_path }}
                  else
                    /usr/libexec/PlistBuddy -c "Add :CACHE_DIR string ${{ inputs.cache_dir }}" ${{ inputs.pref_file_path }}
                  fi
                fi
                
                # Additional preference updates would follow the same pattern
                # Update additional preferences as needed
              fi
            fi
          fi
          
          echo "Preferences file ready at ${{ inputs.pref_file_path }}"
          cat ${{ inputs.pref_file_path }}
          
          # Clear existing preferences to ensure we only use the file
          defaults delete com.github.autopkg 2>/dev/null || true
          
          # Set PREFS_PATH environment variable for subsequent steps
          echo "PREFS_PATH=${{ inputs.pref_file_path }}" >> $GITHUB_ENV
      
      - name: Configure Munki preferences via defaults
        if: ${{ inputs.use_pref_file != true }}
        run: |
          # Set Munki repo path for AutoPkg using defaults command
          defaults write com.github.autopkg MUNKI_REPO ${{ inputs.munki_repo_path }}
          echo "MUNKI_REPO set to ${{ inputs.munki_repo_path }}"
      
      - name: Add recipe repositories
        id: add-repos
        run: |
          # Add the core AutoPkg recipe repository
          echo "Adding core AutoPkg recipe repository..."
          
          # Check if we're using external prefs file
          if [ -n "$PREFS_PATH" ]; then
            PREFS_ARG="--prefs $PREFS_PATH"
            echo "Using external preferences file: $PREFS_PATH"
            autopkg repo-add recipes $PREFS_ARG
          else
            autopkg repo-add recipes
          fi
          
          # Initialize repo counter
          REPO_COUNT=1
          
          # Add additional repositories if specified
          if [ -n "${{ inputs.recipe_repos }}" ]; then
            IFS=',' read -ra REPOS <<< "${{ inputs.recipe_repos }}"
            for REPO in "${REPOS[@]}"; do
              echo "Adding recipe repository: $REPO"
              if [ -n "$PREFS_ARG" ]; then
                autopkg repo-add "$REPO" $PREFS_ARG
              else
                autopkg repo-add "$REPO"
              fi
              REPO_COUNT=$((REPO_COUNT+1))
            done
          fi
          
          echo "repos_count=$REPO_COUNT" >> $GITHUB_OUTPUT
      
      - name: List available recipes
        run: |
          echo "Available recipes:"
          if [ -n "$PREFS_PATH" ]; then
            autopkg list-recipes --prefs $PREFS_PATH
          else
            autopkg list-recipes
          fi
      
      - name: Run specified recipe
        if: ${{ inputs.recipe_name != '' }}
        run: |
          echo "Running recipe: ${{ inputs.recipe_name }}"
          if [ -n "$PREFS_PATH" ]; then
            autopkg run ${{ inputs.recipe_name }} --prefs $PREFS_PATH
          else
            autopkg run ${{ inputs.recipe_name }}
          fi
      
      - name: Upload results
        if: ${{ inputs.recipe_name != '' && inputs.upload_results == true }}
        uses: actions/upload-artifact@v3
        with:
          name: autopkg-results
          path: ~/Library/AutoPkg/Cache/
          retention-days: 5