name: AutoPkg CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allow manual triggering

jobs:
  autopkg:
    runs-on: macos-latest
    
    env:
      # Debug settings
      DEBUG: "true"
      
      # Recipe configuration
      RECIPE: "Firefox.recipe, Chrome.recipe"
      OVERRIDES_DIR: "./overrides"
      
      # Verification settings
      DISABLE_VERIFICATION: "true"
      FORCE_UPDATE: "true"
      FAIL_RECIPES: "false"
      
      # Report configuration
      REPORT_PATH: "/tmp/autopkg-report.plist"
      
      # Uploader selection
      USE_INTUNE_UPLOADER: "true"
      
      # Intune credentials
      INTUNE_TENANT_ID: ${{ secrets.INTUNE_TENANT_ID }}
      INTUNE_CLIENT_ID: ${{ secrets.INTUNE_CLIENT_ID }}
      INTUNE_CLIENT_SECRET: ${{ secrets.INTUNE_CLIENT_SECRET }}
      
      # Repository configuration
      AUTOPKG_REPOS: "recipes,almenscorner/autopkg-recipes"
      
      # Cleanup and promotion
      CLEANUP_LIST: "./config/cleanup.json"
      PROMOTE_LIST: "./config/promote.json"
      
      # Teams notification
      TEAMS_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK }}
      
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - name: Install dependencies
        run: go get -v ./...
      
      - name: Build AutoPkg setup tool
        run: |
          cd tools/cmd/autopkg_setup
          go build -v -o autopkg-setup
      
      - name: Run SetupGitHubActionsRunner
        run: ./tools/cmd/autopkg_setup/autopkg-setup
      
      # - name: Run AutoPkg recipes
      #   run: |
      #     # Run the recipes specified in the RECIPE environment variable
      #     /usr/local/bin/autopkg run $RECIPE -v
      
      # - name: Archive AutoPkg Report
      #   if: always()
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: autopkg-report
      #     path: ${{ env.REPORT_PATH }}