name: AutoPkg CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allow manual triggering

jobs:
  autopkg:
    runs-on: macos-latest
    
    env:
      # Autopkg + pipelin Debug mode
      DEBUG: "true"
      # Enable usage of latest autopkg beta version
      USE_BETA: "true"
      # GitHub token for API access
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Recipe configuration
      RECIPE: "Firefox.recipe, Chrome.recipe"
      OVERRIDES_DIR: "./overrides"
      # Report configuration
      REPORT_PATH: "/tmp/autopkg-report.plist"
      # Recipe Verification settings
      DISABLE_VERIFICATION: "true"
      FORCE_UPDATE: "true"
      FAIL_RECIPES: "false"
      # Cleanup and promotion lists
      CLEANUP_LIST: "./config/cleanup.json"
      PROMOTE_LIST: "./config/promote.json"
      # MDM Uploader selection
      USE_INTUNE_UPLOADER: "true"
      USE_JAMF_UPLOADER: "false"
      # Intune credentials
      INTUNE_TENANT_ID: ${{ secrets.INTUNE_TENANT_ID }}
      INTUNE_CLIENT_ID: ${{ secrets.INTUNE_CLIENT_ID }}
      INTUNE_CLIENT_SECRET: ${{ secrets.INTUNE_CLIENT_SECRET }}
      # Jamf credentials (included but not used if USE_JAMF_UPLOADER is false)
      JAMFPRO_URL: ${{ secrets.JAMFPRO_URL }}
      JAMFPRO_CLIENT_ID: ${{ secrets.JAMFPRO_CLIENT_ID }}
      JAMFPRO_CLIENT_SECRET: ${{ secrets.JAMFPRO_CLIENT_SECRET }}
      API_USERNAME: ${{ secrets.API_USERNAME }}
      API_PASSWORD: ${{ secrets.API_PASSWORD }}
      SMB_URL: ${{ secrets.SMB_URL }}
      SMB_USERNAME: ${{ secrets.SMB_USERNAME }}
      SMB_PASSWORD: ${{ secrets.SMB_PASSWORD }}
      JCDS2_MODE: "false"
      # Repository configuration
      AUTOPKG_REPOS: "recipes,almenscorner/autopkg-recipes"
      # Teams notification
      TEAMS_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK }}
      # Private repo config
      PRIVATE_REPO_URL: ""
      PRIVATE_REPO_PATH: ""
      
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      
      - name: Set up Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version: '>=1.22.5'
      
      - name: Install dependencies
        run: go get -v ./...
      
      - name: Build AutoPkg setup tool
        run: |
          cd tools/cmd/autopkg_setup
          go build -v -o autopkg-setup
      
      - name: Run SetupGitHubActionsRunner
        run: ./tools/cmd/autopkg_setup/autopkg-setup
      
      # - name: Run AutoPkg recipes
      #   run: |
      #     # Run the recipes specified in the RECIPE environment variable
      #     /usr/local/bin/autopkg run $RECIPE -v
      
      # - name: Archive AutoPkg Report
      #   if: always()
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: autopkg-report
      #     path: ${{ env.REPORT_PATH }}