name: '⚙️ setup and install suspicious package'

on:
  workflow_call:
    inputs:
      debug:
        description: 'Enable debug mode'
        required: false
        default: 'true'
        type: string
      force_update:
        description: 'Force update Suspicious Package'
        required: false
        default: 'true'
        type: string
      suspicious_package_url:
        description: 'URL to download Suspicious Package DMG'
        required: false
        default: 'https://mothersruin.com/software/downloads/SuspiciousPackage.dmg'
        type: string
      sp_download_path:
        description: 'Path to download the Suspicious Package DMG'
        required: false
        default: '/tmp/SuspiciousPackage.dmg'
        type: string

jobs:
  suspiciouspackage:
    runs-on: macos-latest
    env:
      DEBUG: ${{ inputs.debug }}
      FORCE_UPDATE: ${{ inputs.force_update }}
      SUSPICIOUS_PACKAGE_URL: ${{ inputs.suspicious_package_url }}
      SP_DOWNLOAD_PATH: ${{ inputs.sp_download_path }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      
      - name: Set up Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version: '>=1.22.5'

      - name: Install dependencies
        run: go get -v ./...

      - name: Build Suspicious Package setup tool
        run: |
          cd tools/cmd/suspicious_package_setup
          go build -v -o suspiciouspackage-setup

      - name: Run SetupGitHubActionsRunner for Suspicious Package
        run: ./tools/cmd/suspicious_package_setup/suspiciouspackage-setup
